# POC target: systemd container (sshd + httpd). "Service down" = httpd stopped;
# remediation = systemctl restart httpd. Managed by Ansible via the 'ansible' user.
FROM registry.access.redhat.com/ubi9/ubi-init:latest

RUN dnf -y install openssh-server httpd sudo && dnf clean all \
 && systemctl enable sshd httpd \
 && useradd -m -s /bin/bash ansible \
 && echo 'ansible ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ansible \
 && mkdir -p /home/ansible/.ssh && chmod 700 /home/ansible/.ssh

COPY authorized_keys /home/ansible/.ssh/authorized_keys
RUN chown -R ansible:ansible /home/ansible/.ssh \
 && chmod 600 /home/ansible/.ssh/authorized_keys \
 && echo '<h1>app OK</h1>' > /var/www/html/index.html

EXPOSE 22 80
CMD ["/sbin/init"]
